service: post-roe-sls

provider:
  name: google
  stage: dev
  runtime: python39
  region: us-central1
  project: 'ohdo-post-roe-359822'
  credentials: ~/.gcloud/ohdo-post-roe-359822-keyfile.json

frameworkVersion: '2'
plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  search-clinics:
    handler: search_clinics
    events:
      - http: path
  get-drive-time:
    handler: get_drive_time
    events:
      - http: path
  process-async:
    handler: process_async
    events:
      - http: path
    memorySize: 2048
    timeout: 540s

    